/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HaspCiha;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author adilson.pereira
 */
public class TelaCargaXls extends javax.swing.JFrame {
    File file;
    Workbook workbook;
    /**
     * Creates new form TelaCargaXls
     */
    public TelaCargaXls() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcaminho = new javax.swing.JTextField();
        btnxls = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnpreencher = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblcaminhoActionPerformed(evt);
            }
        });

        btnxls.setText("Importar xls");
        btnxls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxlsActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cd_pront", "nome", "Sexo", "dt_nasc", "endereco", "cep", "complem", "dt_ate", "cd_sus"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        btnpreencher.setText("Preencher");
        btnpreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreencherActionPerformed(evt);
            }
        });

        jButton2.setText("Exportar arquivo");

        jLabel1.setText("SOFTWARE REMOVER DE CARACTERES CIHA HASP");

        jButton1.setText("Remover Todos Caracteres");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Caminho do arquivo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(127, 127, 127)
                .addComponent(jButton2)
                .addGap(401, 401, 401))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(lblcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnxls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpreencher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnxls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpreencher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblcaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblcaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcaminhoActionPerformed

    private void btnxlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxlsActionPerformed
        
        // Início do código CIHA
        JFileChooser fc = new JFileChooser();
        fc.setPreferredSize(new Dimension (750, 400));
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = fc.showOpenDialog(this);
        
        if (resultado == JFileChooser.CANCEL_OPTION){
            //JANELA SERÁ FECHADA SEM NENHUMA AÇÃO.
        } else{
            file = fc.getSelectedFile();
            lblcaminho.setText(file.toString().trim());
        }
    }//GEN-LAST:event_btnxlsActionPerformed

    private void btnpreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreencherActionPerformed
        try {
            //// Início do código btnpreencher
            workbook = Workbook.getWorkbook(new File(lblcaminho.getText().trim()));
            //// Fim do código btnpreencher
        } catch (IOException | BiffException ex) {
            Logger.getLogger(TelaCargaXls.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Sheet sheet = workbook.getSheet(0);
        
        //Nome da planilha dentro da celula
       // Cell c0 = sheet.getCell(0, 0);
       // String titulo = c0.getContents();
        
       // lblnomeplanilha.setText(titulo);
        int linhas = sheet.getRows();
        
        ////inicio do for
        for (int i = 2; i < linhas; i++){
            Cell ca = sheet.getCell(0, i);
            Cell cb = sheet.getCell(1, i);
            Cell cc = sheet.getCell(2, i);
            Cell cd = sheet.getCell(3, i);
            Cell ce = sheet.getCell(4, i);
            Cell cf = sheet.getCell(5, i);
            Cell cg = sheet.getCell(6, i);
            Cell ch = sheet.getCell(7, i);
            Cell ci = sheet.getCell(8, i); 
            
            String cd_pront = ca.getContents();
            String nome = cb.getContents();
            String sexo = cc.getContents();
            String dt_nasc = cd.getContents();
            String endereco = ce.getContents();
            String cep = cf.getContents();
            String complem = cg.getContents();
            String dt_ate = ch.getContents();
            String cd_sus = ci.getContents();
            
          
            
            DefaultTableModel mp = (DefaultTableModel) tbl.getModel();
            mp.addRow(new String[] {cd_pront, nome, sexo, dt_nasc, endereco, cep, complem, dt_ate, cd_sus});
                     
        } //// fim do for
            workbook.close();
            
    }//GEN-LAST:event_btnpreencherActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Erro, não foi possível executar.", "ERRO", JOptionPane.WARNING_MESSAGE);
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed
        //// fim do código
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCargaXls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpreencher;
    private javax.swing.JButton btnxls;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblcaminho;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
